/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#faf4ff",
        "on-primary": "#f4f1ff",
        "error-container": "#f74b6d",
        "surface": "#faf4ff",
        "primary-container": "#9396ff",
        "inverse-primary": "#8083ff",
        "secondary-fixed": "#ffc1d6",
        "on-secondary": "#ffeff2",
        "tertiary-container": "#ff8ed2",
        "outline": "#79719d",
        "surface-container": "#ece4ff",
        "tertiary-fixed": "#ff8ed2",
        "on-tertiary": "#ffeef4",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#8387ff",
        "surface-container-low": "#f4eeff",
        "on-secondary-container": "#8e0054",
        "primary-fixed": "#9396ff",
        "secondary": "#b00d6a",
        "on-surface-variant": "#5e5680",
        "on-surface": "#302950",
        "primary": "#4647d3",
        "error": "#b41340",
        "tertiary": "#963776",
        "surface-container-high": "#e6deff",
        "inverse-surface": "#0f072e",
        "on-error": "#ffefef",
        "surface-tint": "#4647d3",
        "background": "#faf4ff",
        "surface-container-highest": "#e1d8ff",
        "secondary-container": "#ffc1d6",
        "inverse-on-surface": "#a097c5",
        "surface-variant": "#e1d8ff",
        "tertiary-fixed-dim": "#ef81c4",
        "outline-variant": "#b0a7d6",
        "surface-dim": "#d8ceff",
        "on-background": "#302950",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}