spring.application.name=social-app

# Neo4j
spring.neo4j.uri=${NEO4J_URI}
spring.neo4j.authentication.username=${NEO4J_USERNAME}
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

#spring.neo4j.uri=${NEO4J_URI}
#spring.neo4j.authentication.username=${NEO4J_USERNAME}
#spring.neo4j.authentication.password=${NEO4J_PASSWORD}

spring.data.neo4j.repositories.type=auto

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# App JWT
app.jwt.secret=${JWT_SECRET:your-256-bit-secret-key-change-in-production}
app.jwt.access-expiry-ms=3600000
app.jwt.refresh-expiry-ms=604800000

# MinIO
app.minio.url=${MINIO_URL:http://localhost:9000}
app.minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
app.minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
app.minio.bucket=${MINIO_BUCKET:socialapp}


#  Server
server.port=8080
server.servlet.context-path=/

#  Logging
logging.level.com.socialapp=DEBUG
logging.level.org.springframework.data.neo4j=WARN

# URL truy c?p Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
